export const mots = [
    "Mystere",
    "Aventure",
    "Exploration",
    "Curiosite",
    "Univers",
    "Inconnu",
    "Decouverte",
    "Melodie",
    "Secret",
    "Astronaute",
    "Phenomene",
    "Xylophone",
    "Exotique",
    "Ecologie",
    "Peripetie",
    "Horizon",
    "Intrigue",
    "Mystique",
    "Paradoxal",
    "Enigme",
    "Question",
    "Labyrinthe",
    "Cascade",
    "Revelation",
    "Chaos",
    "Quotidien",
    "Symbole",
    "Fantaisie",
    "Liberte",
    "Technologie"
];

export const descriptions = [
    "Un secret ou une énigme difficile à élucider.",
    "Une expérience excitante, souvent parsemée de défis.",
    "La découverte de territoires inconnus ou de nouvelles idées.",
    "L'envie d'apprendre, de découvrir, souvent incontrôlable.",
    "L'ensemble de tout ce qui existe, souvent au-delà de notre compréhension.",
    "Ce qui reste à découvrir, un territoire non exploré.",
    "La trouvaille d'un élément nouveau et fascinant.",
    "Une séquence harmonieuse de sons, capable de captiver l’âme.",
    "Une information cachée, difficile à percer.",
    "Un explorateur de l'espace, à la recherche de réponses aux mystères célestes.",
    "Un événement inhabituel, difficile à expliquer.",
    "Un instrument de musique aux sonorités cristallines.",
    "Quelque chose d'étrange, de fascinant, souvent inhabituel.",
    "L'étude des interactions entre les êtres vivants et leur environnement.",
    "Un tournant inattendu dans une histoire ou un événement.",
    "La ligne apparente où le ciel semble rencontrer la terre.",
    "Une situation complexe, souvent pleine de mystères et de rebondissements.",
    "Relatif à des connaissances ésotériques ou mystérieuses.",
    "Qui contient une contradiction ou une énigme apparente.",
    "Un défi intellectuel à résoudre.",
    "Une requête posée pour obtenir des informations.",
    "Un dédale de chemins complexes et sinueux.",
    "Une chute d'eau souvent spectaculaire.",
    "La révélation d'un fait caché ou d'une vérité.",
    "Un état de confusion ou de désordre.",
    "Ce qui concerne le quotidien, la vie de tous les jours.",
    "Un signe représentatif ou emblématique.",
    "L'imagination ou la création sans limites.",
    "La capacité d'agir ou de penser sans restrictions.",
    "L'étude des outils et des méthodes pour résoudre des problèmes."
];
